variavel = input("Digita alguma coisa: ")
print(f"O tipo primitivo dessa variavel é {type(variavel)}")
print(f"Só tem espaços? {variavel.isspace()}")
print(f"É um numero? {variavel.isalnum()}")
print(f"É alfabético? {variavel.isalpha()}")
print(f"É alfanumérico? {variavel.isalnum()}")
print(f"Esta em maiusculas ? {variavel.isupper()}")
print(f"Esta em minusculas? {variavel.islower()}")
print(f"Esta capitalizada? {variavel.istitle()}")